# Getting started with Python

## Asking for help

We have various ways to get help on the documentation of python using codes.


### help

We can type help(object) to see the documentation of what is and what the object can do, like if the object was a function.

````
help(len)
````

The help function works too if we type:

````
object? # look for the documentation of the object
````

````
object?? # look for the code of the object(doesn't work every time)
````


### dir and tab

When using dir or tab, we can see all the objects that we can work wich ones the names matches wich the specified string we are looking for.


## Errors and Debugging

When a exception is raised, we can have control on how these informations will be showed on the screen, with the ````%xmode```` code.

````%xmode```` can be ````Plain````, ````Context````, ````Verbose````.

We can use the ````%debug```` to debug our code, writing ``up`` to go to the next frame, ``down`` to go to the previous frame and ``quit`` to quit the debbuger.

## Functions

We can declare functions with ``def`` keyword, declare optional parameters at the final of the function declaration, and if the funcion is called passing a value for this parameter, the default value will be overwritten by the new one.

In [ ]:
def sumWithArgs(*values, margin = 0):
    return sum(values) + margin

print(sumWithArgs(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, margin=0.5))

In [ ]:
array_of_dict = [
    {"name": "William", "age": 18, "email": "williambruno@gmail.com"}, 
    {"name": "Joao", "age":19, "email": "joao@gmail.com"}
]

for person in array_of_dict:
    print(person['name'])
    print(person['age'])
    print(person['email'])

# Handling with CSV files

In [ ]:
import csv
with open('./mpg.csv', 'r+', encoding='utf-8') as csvfile:
    reader = list(csv.DictReader(csvfile))
    horsepower = 0
    
    for car in reader:
        if car['horsepower'] == '?':
            car['horsepower'] = 0
        horsepower += int(car['horsepower'])
            
    print('Average of horsepower: %.2f ' % (horsepower / len(reader)))

# OOP with Python

## classes

Classes are molds to objects construction. We don't have data encapsulation, so if we want to assign some variable or method that shouldn't be accessible for the user, we declare it with a ``_`` at the beiigining.

In [ ]:
class Person:
    def __init__(self, name, age, email, location):
        self._name = name
        self._age = age
        self._email = email
        self._location = location
    
    def set_name(self, name):
        self._name = name
        pass
    
    def set_age(self, age):
        self._age = age
        pass
    
    def set_email(self, email):
        self._email = email
        pass
    
    def set_location(self, location):
        self._location = location
        pass
    
    def get_name(self):
        return self._name
    
    def get_age(self):
        return self._age
    
    def get_email(self):
        return self._email
    
    def get_location(self):
        return self._location

# Map function using Python

Map function iterates over arguments executting a function passed as argument.

``map(function, iterable1_of_the_function, iterable1_of_the_function, ...)``

It's important to say, the iterables will be passed as arguments for the function inside the map declaration. So, if you pass to many iterables than the function can hold, it will generate an error.

In [ ]:
store1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
store2 = [11, 12, 13, 14, 15, 16, 7, 8, 9, 10]
map_store = map(min, store1, store2)

for value in map_store:
    print(value)

# Lists Comprehensions

Easisest, faster and simple way to declare a list in Python.

``[variable_of_the_list for iterable in range()/data_structure]``

In [ ]:
def count_negatives(nums):
  return len([num for num in nums if num < 0])

squares = [n**2 for n in range(10)]
print(squares)

planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
short_planets = [planet for planet in planets if len(planet) < 6]

print(short_planets)

loud_short_planets = [planet.upper() for planet in planets if len(planet) < 6]

print(loud_short_planets)
print(count_negatives([-1, -2, -3, 4, 5, 6]))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['Venus', 'Earth', 'Mars']
['VENUS', 'EARTH', 'MARS']
3


# Lambda functions in Python

Lambda allow us to create anonymous functions, wich has no name, only implementation.

In [ ]:
minor_prices = list(map(lambda value_1, value_2 : value_1 + value_2, store1, store2))
print(minor_prices)

# NumPy Introduction

Numpy is the fundamental package (library) for creating data structures, manipulating and loading other data. 

In this lection, we will see how to create arrays using numpy, manipulate data, select elements and load datasets.

In [ ]:
import numpy as np
import math
# Arrays in Python are lists and we can pass them as arguments to the array method of the np library

a = np.array([1, 2, 3])
print(a)
# We can see the dimnension of an array with the 'ndim' attribute 
print(a.ndim)

[1 2 3]
1


In [ ]:
# A two dimensional array which is a list of lists is also called matrix
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# We can also check the shape of our array and the type of the data
print(a.shape)
print(b.shape)

print(a.dtype)
print(b.dtype)

(3,)
(2, 3)
int64
int64


In [ ]:
# We can create arrays with placeholders, such as zeros, ones and random numbers
d = np.zeros((3, 3))
print(d)

e = np.ones((3, 3))
print(e)

f = np.random.rand(3, 3)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.34923412 0.19696612 0.34115451]
 [0.02079939 0.44777047 0.82964182]
 [0.18613086 0.13581025 0.75680524]]


In [ ]:
# We can also create an array with values in a range of (starting_value, final_value, difference_between_start_and_final)
print(np.arange(10, 50, 2))

# Also, numpy allow us to create an array with 'n' values lineary spaced between the initial_value 
# and final_value as np.linspace(initial_value, final_value, n)
np.linspace(0, 2, 15)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Operations with Numpy

## Arithmetic Operations

Are all element wise, which means that they are done element by element.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

print(a - b, end='\n\n')
print(a*b, end='\n\n')
print(a/b)

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6], [7, 8, 9]])

print(c + d)

[[ 5  7  9]
 [ 8 10 12]]


In [ ]:
# We have an importante array called the Boolean Array, which one is like a 'map' of each number of an array that returns a boolean for certain condition
celsius = np.array([-1, -2, -15, 0, 20, 30, -50])
celsius > 0

array([False, False, False, False,  True,  True, False])

In [ ]:
# Another application of boolean arrays is when we check the modulus condition
celsius % 2 == 0

array([False,  True, False,  True,  True,  True,  True])

In [ ]:
# We can also manipulate matrices not element wise, but such as in linear algebra
a = np.array([[1, 2, 3], [4, 5, 6], [20, 30, 40]])
b = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(a.shape == b.shape)
print(a@b)

True
[[  66   72   78]
 [ 156  171  186]
 [ 960 1050 1140]]


In [ ]:
# Numpy allow us to make mathmatical checks on arrays
print(a.sum())
print(b.min())
print(a.max())
print(b.mean())

111
7
40
11.0
